# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
laplaceIS_sml2 <- function(y, A, z, lambda0, lambda, transformed_rhos, maxiter, tol, linkFLAG, corrFLAG, grFLAG, ncores, mauto_minM = 100L, mauto_each = 50L, mauto_tol = 1e-5) {
    .Call(`_gllvmSML_laplaceIS_sml2`, y, A, z, lambda0, lambda, transformed_rhos, maxiter, tol, linkFLAG, corrFLAG, grFLAG, ncores, mauto_minM, mauto_each, mauto_tol)
}

#' @export
laplaceIS_sml <- function(y, A, z, lambda0, lambda, transformed_rhos, maxiter, tol, linkFLAG, corrFLAG, grFLAG, ncores) {
    .Call(`_gllvmSML_laplaceIS_sml`, y, A, z, lambda0, lambda, transformed_rhos, maxiter, tol, linkFLAG, corrFLAG, grFLAG, ncores)
}

